source_file_path:
- source/scaled_quant.cu
target_kernel_functions:
- static_scaled_int8_quant_kernel
- dynamic_scaled_int8_quant_kernel
compile_command:
- python3 scripts/task_runner.py --mode compile
correctness_command:
- python3 scripts/task_runner.py --mode correctness
performance_command:
- python3 scripts/task_runner.py --mode performance
task_type: hip2hip
task_result_template: null
prompt:
  source_code: null
  instructions: null
  cheatsheet: null
