source_file_path:
- source/lora_expand_op.py
- source/lora_shrink_op.py
- source/fused_moe_lora_op.py
target_kernel_functions:
- _lora_expand_kernel
- _lora_shrink_kernel
- _fused_moe_lora_kernel
compile_command:
- python3 scripts/task_runner.py --mode compile
correctness_command:
- python3 scripts/task_runner.py --mode correctness
performance_command:
- python3 scripts/task_runner.py --mode performance
task_type: triton2triton
task_result_template: null
prompt:
  source_code: null
  instructions: null
  cheatsheet: null
