source_file_path:
- source/triton_decode_attention.py
target_kernel_functions:
- _fwd_kernel_stage1
- _fwd_kernel_stage2
compile_command:
- python3 scripts/task_runner.py --mode compile
correctness_command:
- python3 scripts/task_runner.py --mode correctness
performance_command:
- python3 scripts/task_runner.py --mode performance
task_type: triton2triton
task_result_template: null
prompt:
  source_code: null
  instructions: null
  cheatsheet: null
